global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector - 主要指標來源
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 3s

  # OpenTelemetry Collector 自身的指標
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s
    metrics_path: /metrics

  # Right Backend application metrics（通過 OpenTelemetry 收集）
  - job_name: 'right-backend-app'
    static_configs:
      - targets: ['right-backend-app:8090']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true

  # Jaeger 內部指標
  - job_name: 'jaeger-internal'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana 內部指標
  - job_name: 'grafana-internal'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics